---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: romana 
  namespace: gallifrey  
  name: romana
spec:
  type: NodePort
  ports:
  - name: romana
    port: 80
    targetPort: 9080
    nodePort: 31998
  selector:
    service: romana
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: romana
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - services
  - secrets
  - endpoints
  - pods  
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: romana
  namespace: gallifrey
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: romana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: romana
subjects:
- kind: ServiceAccount
  name: romana
  namespace: gallifrey
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: gallifrey
  name: romana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: romana
    spec:
      serviceAccountName: romana
      containers:
      - name: romana
        image: cafbr/mytool:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
          protocol: TCP
