apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: romana
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - services
  - secrets
  - endpoints
  - pods  
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: romana
  namespace: gallifrey
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: romana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: romana
subjects:
- kind: ServiceAccount
  name: romana
  namespace: gallifrey
